# Generated by Django 5.0.4 on 2024-05-06 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='facebook',
            new_name='Telegram',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='instagram',
            new_name='VK',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='twitter',
            new_name='WhatsApp',
        ),
        migrations.AddField(
            model_name='profile',
            name='achievements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='mail',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Не указано', max_length=20),
            preserve_default=False,
        ),
    ]
