# Generated by Django 5.0.4 on 2024-05-06 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_notion_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notion',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
