# Generated by Django 5.0.4 on 2024-05-07 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_profile_user_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
