# Generated by Django 5.0.4 on 2024-05-12 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_delete_post'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Telegram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ваш Телеграм'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='VK',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ваш Вконтакте'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='WhatsApp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ваш WhatsApp'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='achievements',
            field=models.TextField(blank=True, null=True, verbose_name='Достижения'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Расскажите о себе'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(max_length=30, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstname',
            field=models.CharField(max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastname',
            field=models.CharField(max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('text', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Текст')),
                ('image', models.FileField(blank=True, null=True, upload_to='', verbose_name='Картинка')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
    ]
