# Generated by Django 5.0.4 on 2024-05-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_alter_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='occupation',
            field=models.CharField(max_length=16, null=True, verbose_name='Род деятельности'),
        ),
    ]
