# Generated by Django 5.0.4 on 2024-05-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_profile_occupation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='occupation',
        ),
    ]
