# Generated by Django 5.0.4 on 2024-04-15 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_homepage_bg_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='bg_image',
            new_name='publish_image',
        ),
    ]
