# Generated by Django 5.0.4 on 2024-04-15 08:08

import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_bg_image_homepage_publish_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('rtfblock', wagtail.blocks.RichTextBlock()), ('imgblock', wagtail.images.blocks.ImageChooserBlock()), ('socialmediablock', wagtail.embeds.blocks.EmbedBlock())], blank=True),
        ),
    ]
