# Generated by Django 5.0.4 on 2024-04-15 10:31

import django.db.models.deletion
import wagtail.blocks
import wagtail.embeds.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homepage_body'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('figcaptionblock', wagtail.blocks.StructBlock([('figure', wagtail.images.blocks.ImageChooserBlock(label='Вставьте КаРтИнКу')), ('caption', wagtail.blocks.CharBlock(label='Добавьте описание по браски жи ес'))])), ('rtfblock', wagtail.blocks.RichTextBlock(help_text='Введите описание', label='Текст')), ('imgblock', wagtail.images.blocks.ImageChooserBlock(label='Вставить картиночку', template='blocks/imgblock.html')), ('streamfieldblock', wagtail.embeds.blocks.EmbedBlock(label='эээ вроде видос какой то вставить можно'))], blank=True),
        ),
    ]
