# Generated by Django 5.0.4 on 2024-04-15 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_reviewpage_alter_homepage_body'),
        ('wagtailcore', '0091_remove_revision_submitted_for_moderation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ReviewPage',
            new_name='AutorizationPage',
        ),
    ]
