# Generated by Django 5.0.4 on 2024-04-15 12:13

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_reviewpage_autorizationpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodytext', wagtail.fields.RichTextField()),
            ],
        ),
    ]
