# Generated by Django 5.0.4 on 2024-04-15 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={'verbose_name': 'Футер', 'verbose_name_plural': 'Футеры'},
        ),
    ]
